### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by halliwells99** [ognistik/km-ai-memos#1]
Couple of issues I've come up against on the shortcut only. I hope you can help Robert.

When I run the shortcut on the Mac it runs successfully but sadly the output language is Welsh! I am from the UK and speak English only.

This is a well-known bug in Whisper - where bizarrely it seems to think UK accents are speaking Welsh. I've spoken to a few developers about the issue and what they have down is explicitly tell Whisper to ask initially on set up what the output language should be. Once you tell Whisper it's English there are no more Welsh hallucinations. This bug has been around for many months.

Secondly I can't seem to get the shortcut to run on my iPhone. I get the error message: "The file "list.txt" couldn't be opened."
I am using the same API key as the Mac and I am using Bear on both the iPhone and the Mac. Hope you can help me out.

<img width="441" alt="Screenshot 2024-10-22 at 12 47 35" src="https://github.com/user-attachments/assets/8945ad96-bce2-4f38-b8c4-5f0b51868e0b">

**Comment by halliwells99** [comment]
Here is a thread from 2023 about this bug.... and a year later it's still not been fixed!!

https://community.openai.com/t/solved-whisper-translates-into-welsh/120780/77

**Comment by ognistik** [comment]
Hi! I've just published a [new release](https://github.com/ognistik/km-ai-memos/releases/latest) which has a language field. You only need to set it up in the Shortcut (it's one of the fields in the top area) and the new version of the KM Macro will read it from there. For English you should just enter the two letter code `en`. I hope this fixes it for you!

The second issue with the phone sounds more like an issue with iCloud sync. Can you go in the Files app, look inside Shortcuts/AI Memos, then can you open list.txt? It should be an empty file, but it's still necessary for everything to work properly. The list.txt file is created once you run the macro once by itself (but it does need to sync up properly to iCloud or it can give you this issue).

I suggest you keep the AI Memos and Just Press Record folders downloaded locally both on your phone and desktop just to avoid issues. Right click or press and hold and select keep downloaded.

Hope this fixes it for you. If not, or if you encounter anything els, let me know!

**Comment by halliwells99** [comment]
Issues have all been resolved with latest update. Thank you so much!!
Appreciate your hard work

**Comment by ognistik** [comment]
Awesome!
