### ISSUE TITLE
Still not always English

### ISSUE THREAD

**Issue by halliwells99** [ognistik/km-ai-memos#2]
Hi, did a few more test runs and roughly one in every 3 recordings is still going out in Welsh translation.
I have put 'en' in the required field of the shortcut, so not sure why Whisper does not default to English?
Strange. See attached for a recording made a few minutes ago

Have you any ideas?
<img width="441" alt="Screenshot 2024-10-22 at 19 54 38" src="https://github.com/user-attachments/assets/2a3a9c37-51ee-4e10-b439-39e30eb99c46">

**Comment by ognistik** [comment]
Some people [in this thread](https://community.openai.com/t/solved-whisper-translates-into-welsh/120780/60) suggest adding a longer prompt in English, aside from the language parameter in `en` . 

I am giving you two screenshots that show you where to add it both in the Shortcut and KM macro. I already wrote a simple prompt in English, but perhaps a longer prompt would help. If that makes a difference let me know and I'll try to add a field to customize the prompt in an easier way in the next release.

For the Shortcut
![CleanShot 2024-10-22 at 13 56 14@2x](https://github.com/user-attachments/assets/b74b85f6-6373-4620-b718-3d5eeff94066)

For the KM macro
![CleanShot 2024-10-22 at 14 03 01@2x](https://github.com/user-attachments/assets/c5798274-2e6e-45cf-9ca7-748f6d86edec)

**Comment by halliwells99** [comment]
Thanks for the suggestions. I'm travelling today and away from my iMac. I will update the macro when I get back at the end of the week and let you know if the issues persist.

**Comment by halliwells99** [comment]
Sorry, been away a few days and finally got round to testing the app again. Everything now in sync and working perfectly. I'm not a huge Bear user so changed the shortcut to work with Apple Notes and it works beautifully. Thanks again for creating this workflow - amazing work.

**Comment by ognistik** [comment]
No worries, thank you so much for testing and I'm glad it's useful!
